// <auto-generated />
namespace LeilaoNaNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Produtos_remove_imagem_addTable_imagemProduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Produtos_remove_imagem_addTable_imagemProduto));
        
        string IMigrationMetadata.Id
        {
            get { return "202102072057562_Produtos_remove_imagem_addTable_imagemProduto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
